### ISSUE TITLE
Compilation problem when using FreeFluidsModlica

### ISSUE THREAD

**Issue by f-beerlage** [CarlosTrujilloGonzalez/FreeFluidsModelica#36]
Hi,

To model and simulate the heat pump of the Builidings library, I need a non-fluorous refrigerant such as propane (new EU directives).

Now I always get this error when I replace the fluid with a refrigerant from FreeFluids (TMedia, LMedia and also ExternalPure)

[C:/OM121/OM64bit/OMCompiler/Compiler/NFFrontEnd/NFCeval.mo: 1089:9-1089:67]: Internal error NFCeval.evalBinaryMul failed to evaluate ‘{0.0, 8.035468558215966e-05}[pressure.n] * 0.0‘

Same error also occurs when I use antifreeze liquids for solar thermal energy

Any idea why this happens? How to fix this?

**Comment by f-beerlage** [comment]
This is the buildings libary: https://github.com/lbl-srg/modelica-buildings

**Comment by CarlosTrujilloGonzalez** [comment]
I had never worked with the Buildings library, but I have installed it and run the example under Buildings.Fluid.HeatPumps.Examples.Carnot_TCon. It is using as medium Buildings.Media.Water, that I see is an extension of Modelica.Media.Water.ConstantPropertyLiquidWater. I have replaced the media with FreeFluids.LMedia.Fluids.Water in OpenModelica and I obtain the followin message:
[1] 13:07:23 Translation Error
Internal error Instantiation of ProvaBuildings.Carnot_TCon failed with no error message
I have tried the old frontend of OpenModelica and the model runs perfectly. The problem with the old frontend of OpenModelica is that it takes a lot the translation to C code.
I have tried also with the ExternalMedia library and CoolProp but it doesn't work with any of the frontends.
Regarding ExternalPure I have observed an issue I didn't thought about: if the library is called from outside FreeFluids the needed C code is not found.
I need to understand how Buildings is using media definition, because, in the package Buildings.Media, air, steam, water and antifreezes are extension of Modelica.Media but, under Refrigerants, R410A is defined with no compatibility with Modelica.Media. So I would think that mediums developed just for Buildings may be needed.
I will spend some time looking at the problem and if I will comment later.

**Comment by f-beerlage** [comment]
Good, thank you. In case only older OM versions are running, could you please tell me which version you are using? If you find out how to modfiy the fluids so that they work with buildings libary that would be so great. 

At the moment i am running simulations with water wihle modelling but I need some of CoolProp fluids for my project (refrigerant, hydrogen, antifreeze, etc.). 

If you ignore the translation errors, then the initinalisation errors I described above will occur later on.


I was also thinking of issuing to buildings or searching similar issues in buildings GitHub, but haven´t had time yet

**Comment by CarlosTrujilloGonzalez** [comment]
You don't need to change your version of OM. It can work with both the new and the old frontends. By default the new frontend is used. In order to switch to the old frontend you only need to go to the Simulation Setup, while editing your model in OMEdit, and, in the Translation Flags tab, check Enable old frontend for code generation. If you want this preference be saved in your model for posterior usage, check also (in the General tab) Save translation flags inside model.
As for my experience the old frontend has less compatibility problems than the new one, but is slower in the translation. It doesn't affect compilation or simulation speeds.
Regarding media models, you can read in the documentation that Buildings.Media. Refrigerants contains the definitions needed for the compressor models. It comes only with the package R410A. For other substances you needed a package that implements exactly the same functions that are implemented in R410A, and that are not included in the Modelica.Media standard functions. Here there are two possibilities: One is to add those functions to a standard Modelica.Media package. The other is to create a package that implements just them.  I will try to add the functions to my TMedia package and check the accuracy. If it is not enough good, I will try to implement them in a dedicated package using the Martin-Hou EOS, as is done in R410A. It will take some days.

**Comment by CarlosTrujilloGonzalez** [comment]
It has been easier than expected. I added the needed funtions to the ExternalPure package and the compressor model runs fine using the OM new frontend. You will find the tests in the subpackage ExternalPure.BuildingsTests of the already updated version of FreeFluids, I have included also a test with propane. The difference between the data calculated with Buildings supplied R410A medium and ExternalPure R410A are minimal, and data from ExternalPure should be prefered as the EOS used is more acurate than the M-H EOS used by Buildings.
For equipment out of compressors, Buildings uses quite standard medium definitions, according to the Modelica.Media standards. I see that there are already included EG-Water and PG-Water among others.

**Comment by f-beerlage** [comment]
Yes compressor works fine, but the ready made Caront Heat Pump is not running. Of course the heat pump could also be modelled with the compressor only, but I wonder why the heat pump model does not work. 
I think you also got the error:

[2] 20:53:02 Translation Error
[FreeFluids.ExternalPure: 182:5-191:17]: External function ‘FF_solveEosM‘ could not be found in any of the given shared libraries:
  C:\Users\flori\AppData\Local\Temp\OpenModelica\OMEdit\/

[3] 20:53:02 Translation Error
[FreeFluids.ExternalPure: 201:9-201:212]: [Failed to evaluate function: FreeFluids.ExternalPure.BuildingsTests.Carnot_TCon.heaPum.con.preDro.Medium.solveEOS.](omeditmessagesbrowser:///FreeFluids.ExternalPure?lineNumber=201)

General question: How can I add fluids myself? I already have a finished solar thermal model (the solar collector Buildings.Fluid.SolarCollectors.EN12975 was used but I added some additional stuff to calculate heat flows better) and still need an antifreeze fluid. With the antifreeze from FreeFluids.Pipes.Examples.Glycol47 I get the same error as described above.

**Comment by f-beerlage** [comment]
> You don't need to change your version of OM. It can work with both the new and the old frontends. By default the new frontend is used. In order to switch to the old frontend you only need to go to the Simulation Setup, while editing your model in OMEdit, and, in the Translation Flags tab, check Enable old frontend for code generation. If you want this preference be saved in your model for posterior usage, check also (in the General tab) Save translation flags inside model. As for my experience the old frontend has less compatibility problems than the new one, but is slower in the translation. It doesn't affect compilation or simulation speeds. Regarding media models, you can read in the documentation that Buildings.Media. Refrigerants contains the definitions needed for the compressor models. It comes only with the package R410A. For other substances you needed a package that implements exactly the same functions that are implemented in R410A, and that are not included in the Modelica.Media standard functions. Here there are two possibilities: One is to add those functions to a standard Modelica.Media package. The other is to create a package that implements just them. I will try to add the functions to my TMedia package and check the accuracy. If it is not enough good, I will try to implement them in a dedicated package using the Martin-Hou EOS, as is done in R410A. It will take some days.

Ok maybe I should check these functions if it is not working. But buildings example Carnot_y with R410a is not working ether. Only the compressors do work

**Comment by CarlosTrujilloGonzalez** [comment]
It is difficult for me to understand what you are doing. The model FreeFluids.ExternalPure.BuildingsTests.Carnot_TCon runs perfectly at least in my computer. The error you get can only be produced if you have changed the medium that I used (from the package TMedia) to one in the package ExternalPure. And my question is: Why do you need to change it?
Buildings seems to be using biphasic media only for the compressors. For all other models it is using very simple monophasic media. For example, the Carnot_TCon runs perfectly with the  Buildings.Media.Water medium, that is an extension of Modelica.Media.Water.ConstantPropertyLiquidWater, a simple monophasic medium.
Use the mediums in ExternalPure just for the compressors, for the other equipment use simpler mediums, as those in Buildings.Media (except the subpackage Refrigerants). There you have EG-Water and PG-Water antifreezes.
I have also tested the medium  FreeFluids.Pipes.Examples.Glycol47 in the Buildings.Fluid.SolarCollectors.Examples.Concentrating example and runs OK. Which version of OpenModelica are you using?

**Comment by f-beerlage** [comment]
It's really strange, so when I check the model for errors, the following warnings appear:
[2] 09:29:15 Translation Error
[FreeFluids.ExternalPure: 182:5-191:17]: External function ‘FF_solveEosM‘ could not be found in any of the given shared libraries:
  C:\Users\flori\AppData\Local\Temp\OpenModelica\OMEdit\/

[3] 09:29:15 Translation Error
[FreeFluids.ExternalPure: 201:9-201:212]: [Failed to evaluate function: FreeFluids.ExternalPure.BuildingsTests.Carnot_TCon_TMedia.heaPum.con.preDro.Medium.solveEOS.](omeditmessagesbrowser:///FreeFluids.ExternalPure?lineNumber=201)

But the model is simulated. However, it does not work if I want to change the medium directly, but only with the command redeclare medium... What is very strange is that my computer takes an unusually long time for the calculation. Admittedly I don't have the best one, but normally everything has always worked well. I have the current OM version 1.21.0

**Comment by f-beerlage** [comment]
I would like to model and simulate a larger energy system in which a heat pump and solar thermal energy are present. Individually the models work without any problems but unfortunately not together. This is solar thermal with Carnot_y example from Buildings

`model HeatingSystem2
extends SolarThermal(redeclare package Medium = FreeFluids.Pipes.Examples.Glycol47);
extends HeatPump_Carnot;
end HeatingSystem2;`

The model does not work 

`model HeatingSystem2
extends SolarThermal(redeclare package Medium = FreeFluids.Pipes.Examples.Glycol47);
extends HeatPump_Carnot(redeclare package Medium1 = FreeFluids.TMedia.Fluids.Water, redeclare package Medium2 = FreeFluids.TMedia.Fluids.Propane);
end HeatingSystem2;`

Errors that occur again and again: 

[1] 10:56:37 Translation Error
[C:/OM121/OM64bit/OMCompiler/Compiler/NFFrontEnd/NFCeval.mo: 1089:9-1089:67]: Internal error NFCeval.evalBinaryMul failed to evaluate ‘{0.0, 7.673366162506428e-05}[pressure.n] * 0.0‘

[1] 10:56:41 Translation Error
[C:/OM121/OM64bit/OMCompiler/Compiler/NFFrontEnd/NFCeval.mo: 1089:9-1089:67]: Internal error NFCeval.evalBinaryMul failed to evaluate ‘{0.0, 7.673366162506428e-05}[pressure.n] * 0.0‘

**Comment by f-beerlage** [comment]
Well now I found another way and it works so far. Idk if this a modelica problem or a problem due to the package. Anways thank you very much for your help so far

**Comment by CarlosTrujilloGonzalez** [comment]
Glad you found a solution. The error
[2] 09:29:15 Translation Error
[FreeFluids.ExternalPure: 182:5-191:17]: External function ‘FF_solveEosM‘ could not be found in any of the given shared libraries:
C:\Users\flori\AppData\Local\Temp\OpenModelica\OMEdit/
Is due to the fact that the OM compiler can't find the C code used to implement the function, despite the function is written according to the standard way. Normally there is no problem, but from time to time I find it. I belive it is a bug in the OM implementation.
